import { BookEntry } from '@/features/books/types';

export const newTestamentBooks: BookEntry[] = [
  {
    id: 'mateo',
    testament: 'new',
    orderNumber: 1,
    classificationKey: 'gospels',
    classificationLabel: 'Evangelios',
    name: 'Mateo',
    chapterCount: 28,
    keyPhrase: 'El Mesías.',
  },
  {
    id: 'marcos',
    testament: 'new',
    orderNumber: 2,
    classificationKey: 'gospels',
    classificationLabel: 'Evangelios',
    name: 'Marcos',
    chapterCount: 16,
    keyPhrase: 'El Siervo.',
  },
  {
    id: 'lucas',
    testament: 'new',
    orderNumber: 3,
    classificationKey: 'gospels',
    classificationLabel: 'Evangelios',
    name: 'Lucas',
    chapterCount: 24,
    keyPhrase: 'El Hijo del Hombre.',
  },
  {
    id: 'juan',
    testament: 'new',
    orderNumber: 4,
    classificationKey: 'gospels',
    classificationLabel: 'Evangelios',
    name: 'Juan',
    chapterCount: 21,
    keyPhrase: 'El Hijo de Dios.',
  },
  {
    id: 'hechos',
    testament: 'new',
    orderNumber: 5,
    classificationKey: 'historical_nt',
    classificationLabel: 'Históricos',
    name: 'Hechos',
    chapterCount: 28,
    keyPhrase: 'El Espíritu Santo moviéndose entre los hombres.',
  },
  {
    id: 'romanos',
    testament: 'new',
    orderNumber: 6,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: 'Romanos',
    chapterCount: 16,
    keyPhrase: 'El Justificador.',
  },
  {
    id: '1-corintios',
    testament: 'new',
    orderNumber: 7,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: '1 Corintios',
    chapterCount: 16,
    keyPhrase: 'El Santificador.',
  },
  {
    id: '2-corintios',
    testament: 'new',
    orderNumber: 8,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: '2 Corintios',
    chapterCount: 13,
    keyPhrase: 'El Santificador.',
  },
  {
    id: 'galatas',
    testament: 'new',
    orderNumber: 9,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: 'Gálatas',
    chapterCount: 6,
    keyPhrase: 'El Redentor de la maldición de la ley.',
  },
  {
    id: 'efesios',
    testament: 'new',
    orderNumber: 10,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: 'Efesios',
    chapterCount: 6,
    keyPhrase: 'El Esposo de la Iglesia.',
  },
  {
    id: 'filipenses',
    testament: 'new',
    orderNumber: 11,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: 'Filipenses',
    chapterCount: 4,
    keyPhrase: 'El Gozo de nuestro Corazón.',
  },
  {
    id: 'colosenses',
    testament: 'new',
    orderNumber: 12,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: 'Colosenses',
    chapterCount: 4,
    keyPhrase: 'En quien habita corporalmente la plenitud de la Deidad.',
  },
  {
    id: '1-tesalonicenses',
    testament: 'new',
    orderNumber: 13,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: '1 Tesalonicenses',
    chapterCount: 5,
    keyPhrase: 'Nuestro inminente Rey Venidero.',
  },
  {
    id: '2-tesalonicenses',
    testament: 'new',
    orderNumber: 14,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: '2 Tesalonicenses',
    chapterCount: 3,
    keyPhrase: 'Nuestro inminente Rey Venidero.',
  },
  {
    id: '1-timoteo',
    testament: 'new',
    orderNumber: 15,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: '1 Timoteo',
    chapterCount: 6,
    keyPhrase: 'El Mediador entre Dios y los hombres.',
  },
  {
    id: '2-timoteo',
    testament: 'new',
    orderNumber: 16,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: '2 Timoteo',
    chapterCount: 4,
    keyPhrase: 'El Mediador entre Dios y los hombres.',
  },
  {
    id: 'tito',
    testament: 'new',
    orderNumber: 17,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: 'Tito',
    chapterCount: 3,
    keyPhrase: 'El Pastor Fiel.',
  },
  {
    id: 'filemon',
    testament: 'new',
    orderNumber: 18,
    classificationKey: 'pauline_letters',
    classificationLabel: 'Cartas Paulinas',
    name: 'Filemón',
    chapterCount: 1,
    keyPhrase: 'El Amigo de los oprimidos.',
  },
  {
    id: 'hebreos',
    testament: 'new',
    orderNumber: 19,
    classificationKey: 'general_letters',
    classificationLabel: 'Cartas Generales',
    name: 'Hebreos',
    chapterCount: 13,
    keyPhrase: 'Nuestro Sumo Sacerdote.',
  },
  {
    id: 'santiago',
    testament: 'new',
    orderNumber: 20,
    classificationKey: 'general_letters',
    classificationLabel: 'Cartas Generales',
    name: 'Santiago',
    chapterCount: 5,
    keyPhrase: 'El Sanador de los enfermos.',
  },
  {
    id: '1-pedro',
    testament: 'new',
    orderNumber: 21,
    classificationKey: 'general_letters',
    classificationLabel: 'Cartas Generales',
    name: '1 Pedro',
    chapterCount: 5,
    keyPhrase: 'El Príncipe de los Pastores.',
  },
  {
    id: '2-pedro',
    testament: 'new',
    orderNumber: 22,
    classificationKey: 'general_letters',
    classificationLabel: 'Cartas Generales',
    name: '2 Pedro',
    chapterCount: 3,
    keyPhrase: 'El Príncipe de los Pastores.',
  },
  {
    id: '1-juan',
    testament: 'new',
    orderNumber: 23,
    classificationKey: 'general_letters',
    classificationLabel: 'Cartas Generales',
    name: '1 Juan',
    chapterCount: 5,
    keyPhrase: 'El Amor de Dios derramado en nuestros corazones.',
  },
  {
    id: '2-juan',
    testament: 'new',
    orderNumber: 24,
    classificationKey: 'general_letters',
    classificationLabel: 'Cartas Generales',
    name: '2 Juan',
    chapterCount: 1,
    keyPhrase: 'El Amor de Dios derramado en nuestros corazones.',
  },
  {
    id: '3-juan',
    testament: 'new',
    orderNumber: 25,
    classificationKey: 'general_letters',
    classificationLabel: 'Cartas Generales',
    name: '3 Juan',
    chapterCount: 1,
    keyPhrase: 'El Amor de Dios derramado en nuestros corazones.',
  },
  {
    id: 'judas',
    testament: 'new',
    orderNumber: 26,
    classificationKey: 'general_letters',
    classificationLabel: 'Cartas Generales',
    name: 'Judas',
    chapterCount: 1,
    keyPhrase: 'El Señor que viene con sus millares de Santos.',
  },
  {
    id: 'apocalipsis',
    testament: 'new',
    orderNumber: 27,
    classificationKey: 'prophetic',
    classificationLabel: 'Proféticos',
    name: 'Apocalipsis',
    chapterCount: 22,
    keyPhrase: 'El Rey de Reyes y Señor de Señores.',
  },
];