import { BookEntry } from '@/features/books/types';

export const oldTestamentBooks: BookEntry[] = [
  {
    id: 'genesis',
    testament: 'old',
    orderNumber: 1,
    classificationKey: 'law',
    classificationLabel: 'Libros de la Ley (Pentateuco)',
    name: 'Génesis',
    chapterCount: 50,
    keyPhrase: 'La Simiente de la Mujer.',
  },
  {
    id: 'exodo',
    testament: 'old',
    orderNumber: 2,
    classificationKey: 'law',
    classificationLabel: 'Libros de la Ley (Pentateuco)',
    name: 'Éxodo',
    chapterCount: 40,
    keyPhrase: 'El Cordero Pascual.',
  },
  {
    id: 'levitico',
    testament: 'old',
    orderNumber: 3,
    classificationKey: 'law',
    classificationLabel: 'Libros de la Ley (Pentateuco)',
    name: 'Levítico',
    chapterCount: 27,
    keyPhrase: 'Sumo Sacerdote.',
  },
  {
    id: 'numeros',
    testament: 'old',
    orderNumber: 4,
    classificationKey: 'law',
    classificationLabel: 'Libros de la Ley (Pentateuco)',
    name: 'Números',
    chapterCount: 36,
    keyPhrase: 'La Columna de nube de día, y la Columna de fuego de noche.',
  },
  {
    id: 'deuteronomio',
    testament: 'old',
    orderNumber: 5,
    classificationKey: 'law',
    classificationLabel: 'Libros de la Ley (Pentateuco)',
    name: 'Deuteronomio',
    chapterCount: 34,
    keyPhrase: 'El Profeta mayor que Moisés.',
  },
  {
    id: 'josue',
    testament: 'old',
    orderNumber: 6,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: 'Josué',
    chapterCount: 24,
    keyPhrase: 'El Capitán de nuestra Salvación.',
  },
  {
    id: 'jueces',
    testament: 'old',
    orderNumber: 7,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: 'Jueces',
    chapterCount: 21,
    keyPhrase: 'Nuestro Juez y dador de la Ley.',
  },
  {
    id: 'rut',
    testament: 'old',
    orderNumber: 8,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: 'Rut',
    chapterCount: 4,
    keyPhrase: 'Nuestro Pariente Redentor.',
  },
  {
    id: '1-samuel',
    testament: 'old',
    orderNumber: 9,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: '1 Samuel',
    chapterCount: 31,
    keyPhrase: 'Él es Nuestro Profeta Fiel.',
  },
  {
    id: '2-samuel',
    testament: 'old',
    orderNumber: 10,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: '2 Samuel',
    chapterCount: 24,
    keyPhrase: 'Él es Nuestro Profeta Fiel.',
  },
  {
    id: '1-reyes',
    testament: 'old',
    orderNumber: 11,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: '1 Reyes',
    chapterCount: 22,
    keyPhrase: 'Nuestro Rey que gobierna.',
  },
  {
    id: '2-reyes',
    testament: 'old',
    orderNumber: 12,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: '2 Reyes',
    chapterCount: 25,
    keyPhrase: 'Nuestro Rey que gobierna.',
  },
  {
    id: '1-cronicas',
    testament: 'old',
    orderNumber: 13,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: '1 Crónicas',
    chapterCount: 29,
    keyPhrase: 'Nuestro Rey que gobierna.',
  },
  {
    id: '2-cronicas',
    testament: 'old',
    orderNumber: 14,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: '2 Crónicas',
    chapterCount: 36,
    keyPhrase: 'Nuestro Rey que gobierna.',
  },
  {
    id: 'esdras',
    testament: 'old',
    orderNumber: 15,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: 'Esdras',
    chapterCount: 10,
    keyPhrase: 'Nuestro Escriba Fiel.',
  },
  {
    id: 'nehemias',
    testament: 'old',
    orderNumber: 16,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: 'Nehemías',
    chapterCount: 13,
    keyPhrase: 'El Constructor de los muros derribados.',
  },
  {
    id: 'ester',
    testament: 'old',
    orderNumber: 17,
    classificationKey: 'historical',
    classificationLabel: 'Libros históricos',
    name: 'Ester',
    chapterCount: 10,
    keyPhrase: 'Nuestro Mardoqueo.',
  },
  {
    id: 'job',
    testament: 'old',
    orderNumber: 18,
    classificationKey: 'poetic',
    classificationLabel: 'Libros poéticos',
    name: 'Job',
    chapterCount: 42,
    keyPhrase: 'Nuestro redentor que vive.',
  },
  {
    id: 'salmos',
    testament: 'old',
    orderNumber: 19,
    classificationKey: 'poetic',
    classificationLabel: 'Libros poéticos',
    name: 'Salmos',
    chapterCount: 150,
    keyPhrase: 'Jehová nuestro Pastor.',
  },
  {
    id: 'proverbios',
    testament: 'old',
    orderNumber: 20,
    classificationKey: 'poetic',
    classificationLabel: 'Libros poéticos',
    name: 'Proverbios',
    chapterCount: 31,
    keyPhrase: 'Nuestra Sabiduría.',
  },
  {
    id: 'eclesiastes',
    testament: 'old',
    orderNumber: 21,
    classificationKey: 'poetic',
    classificationLabel: 'Libros poéticos',
    name: 'Eclesiastés',
    chapterCount: 12,
    keyPhrase: 'Nuestra Sabiduría.',
  },
  {
    id: 'cantares',
    testament: 'old',
    orderNumber: 22,
    classificationKey: 'poetic',
    classificationLabel: 'Libros poéticos',
    name: 'Cantares',
    chapterCount: 8,
    keyPhrase: 'Nuestro Amado y nuestro Esposo.',
  },
  {
    id: 'isaias',
    testament: 'old',
    orderNumber: 23,
    classificationKey: 'major_prophets',
    classificationLabel: 'Profetas mayores',
    name: 'Isaías',
    chapterCount: 66,
    keyPhrase: 'El Príncipe de Paz.',
  },
  {
    id: 'jeremias',
    testament: 'old',
    orderNumber: 24,
    classificationKey: 'major_prophets',
    classificationLabel: 'Profetas mayores',
    name: 'Jeremías',
    chapterCount: 52,
    keyPhrase: 'Nuestro Profeta que gime.',
  },
  {
    id: 'lamentaciones',
    testament: 'old',
    orderNumber: 25,
    classificationKey: 'major_prophets',
    classificationLabel: 'Profetas mayores',
    name: 'Lamentaciones',
    chapterCount: 5,
    keyPhrase: 'Nuestro Profeta que gime.',
  },
  {
    id: 'ezequiel',
    testament: 'old',
    orderNumber: 26,
    classificationKey: 'major_prophets',
    classificationLabel: 'Profetas mayores',
    name: 'Ezequiel',
    chapterCount: 48,
    keyPhrase: 'Figura de Cuatro Seres Vivientes.',
  },
  {
    id: 'daniel',
    testament: 'old',
    orderNumber: 27,
    classificationKey: 'major_prophets',
    classificationLabel: 'Profetas mayores',
    name: 'Daniel',
    chapterCount: 12,
    keyPhrase: 'Cuarto Hombre en el horno de fuego.',
  },
  {
    id: 'oseas',
    testament: 'old',
    orderNumber: 28,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Oseas',
    chapterCount: 14,
    keyPhrase: 'El Esposo eterno.',
  },
  {
    id: 'joel',
    testament: 'old',
    orderNumber: 29,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Joel',
    chapterCount: 3,
    keyPhrase: 'El Bautizador en el Espíritu Santo.',
  },
  {
    id: 'amos',
    testament: 'old',
    orderNumber: 30,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Amós',
    chapterCount: 9,
    keyPhrase: 'El que lleva nuestras cargas.',
  },
  {
    id: 'abdias',
    testament: 'old',
    orderNumber: 31,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Abdías',
    chapterCount: 1,
    keyPhrase: 'Nuestro Salvador.',
  },
  {
    id: 'jonas',
    testament: 'old',
    orderNumber: 32,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Jonás',
    chapterCount: 4,
    keyPhrase: 'El gran Misionero foráneo.',
  },
  {
    id: 'miqueas',
    testament: 'old',
    orderNumber: 33,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Miqueas',
    chapterCount: 7,
    keyPhrase: 'Que será Señor en Israel.',
  },
  {
    id: 'nahum',
    testament: 'old',
    orderNumber: 34,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Nahúm',
    chapterCount: 3,
    keyPhrase: 'El Mensajero de hermosos pies. Nuestro Vengador.',
  },
  {
    id: 'habacuc',
    testament: 'old',
    orderNumber: 35,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Habacuc',
    chapterCount: 3,
    keyPhrase: 'El Evangelista que clama por arrepentimiento.',
  },
  {
    id: 'sofonias',
    testament: 'old',
    orderNumber: 36,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Sofonías',
    chapterCount: 3,
    keyPhrase: 'El Señor Poderoso para Salvar.',
  },
  {
    id: 'hageo',
    testament: 'old',
    orderNumber: 37,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Hageo',
    chapterCount: 2,
    keyPhrase: 'El Restaurador de la herencia perdida.',
  },
  {
    id: 'zacarias',
    testament: 'old',
    orderNumber: 38,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Zacarías',
    chapterCount: 14,
    keyPhrase: 'Él es el futuro Rey de Sion. El Manantial abierto de la Casa de David.',
  },
  {
    id: 'malaquias',
    testament: 'old',
    orderNumber: 39,
    classificationKey: 'minor_prophets',
    classificationLabel: 'Profetas menores',
    name: 'Malaquías',
    chapterCount: 4,
    keyPhrase: 'El Sol de Justicia.',
  },
];